server:
  port: 8081

eureka:
  instance:
    hostname=localhost:
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
#      1.0 means 100 percent
